language: node_js
os:
  - linux
  - osx
node_js:
  - 'lts/*'
  - '10'
before_install:
  - npm install -g npm@latest
install:
  - npm install
script:
  - npm run lint
after_success:
  - npm run lh -- --perf=90 --pwa=100 --no-comment https://ljlm0402.netlify.com//
branches:
  only:
    - master
